
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/ASUS/AppData/Local/Programs/Python/Python312/Lib/site-packages/cmake/data/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:66 (project)"
    message: |
      The system is: Windows - 10.0.22621 - AMD64
...
